name: npm test
on: 
  workflow_dispatch:
               
jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: Adding actions/checkout@v4 from marketplace
        uses: actions/checkout@v4