name: npm test
on: 
  workflow_dispatch:
               
jobs:
  job1:
    runs-on: ubuntu-latest

    steps: 
      - name: Adding actions/checkout@v4 from marketplace
        uses: actions/checkout@v4
        with:
          node-version: 'lts/*'
      - name: Adding Node.js from marketplace
        uses: actions/setup-node@v4
      - name: Run "npm install"
        run: npm install
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps: 
      - name: Adding actions/checkout@v4 from marketplace
        uses: actions/checkout@v4
        with:
          node-version: 'lts/*'
      - name: Run "npm install and test"
        run: npm install && npm test