name: interact with Github API
on: 
  pull_request:

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch GITHUB token
        id: github_token
        run: echo "GITHUB_TOKEN=${{GITHUB.TOKEN}}" >> $GITHUB_OUTPUT
      - name: set shot_sha
        id: set_short_sha
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      - name: create issue with GITHUB API
        run: curl --request POST \
            --url https://api.github.com/repos/<specify your repo with github context>/issues \
            --header 'authorization: Bearer ${{steps.github_token.outputs.GITHUB_TOKEN}}' \
            --header 'content-type: application/json' \
            --data '{
              "title": "Automated issue for commit: ${{ steps.short_sha.outputs.sha_short }}",
              "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ steps.short_sha.outputs.sha_short }}_."
              }' \
            --fail